import { ADMIN, INSTRUCTOR, SUPER_ADMIN } from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'
import { NAV_ITEM_TYPE_ITEM } from '@/constants/navigation.constant'

const navigationConfig: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.dashboard',
        icon: 'apps',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, SUPER_ADMIN],
        subMenu: [],
    },
    {
        key: 'roles',
        path: '/roles',
        title: 'Quản lý nhóm quyền',
        translateKey: 'nav.roles',
        icon: 'roles',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [SUPER_ADMIN],
        subMenu: [],
    },
    {
        key: 'instructors',
        path: '/instructors',
        title: 'Quản lý giảng viên',
        translateKey: 'nav.instructors',
        icon: 'instructors',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, SUPER_ADMIN],
        subMenu: [],
    },
    {
        key: 'categories',
        path: '/categories',
        title: 'Quản lý danh mục',
        translateKey: 'nav.categories',
        icon: 'categories',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, SUPER_ADMIN],
        subMenu: [],
    },
    {
        key: 'courses',
        path: '/courses',
        title: 'Quản lý khóa học',
        translateKey: 'nav.courses',
        icon: 'courses',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, SUPER_ADMIN, INSTRUCTOR],
        subMenu: [],
    },
    {
        key: 'students',
        path: '/students',
        title: 'Quản lý học viên',
        translateKey: 'nav.students',
        icon: 'students',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, SUPER_ADMIN],
        subMenu: [],
    },
    {
        key: 'orders',
        path: '/orders',
        title: 'Quản lý đơn hàng',
        translateKey: 'nav.orders',
        icon: 'orders',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, SUPER_ADMIN],
        subMenu: [],
    },
    {
        key: 'instructor-income-monthly',
        path: '/instructor-income-monthly',
        title: 'Thu nhập giảng viên',
        translateKey: 'nav.instructorIncome',
        icon: 'analytics',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, SUPER_ADMIN],
        subMenu: [],
    },
    {
        key: 'analytics',
        path: '/analytics',
        title: 'Báo cáo thống kê',
        translateKey: 'nav.analytics',
        icon: 'analytics',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, SUPER_ADMIN],
        subMenu: [],
    },
]

export default navigationConfig
